In [2]:
import numpy as np

In [7]:
def ex1(n):
    return np.diag(np.arange(1, n + 1))

n  = int(input())
print(ex1(n))

5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
def ex2(n):
    res = np.zeros(n * n, dtype=int)
    res[1::2] = 1
    return res.reshape(n, n)
    
n = int(input())
print(ex2(n))

5
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


In [23]:
def ex3(n, m, r, c):
    res = np.ones((n, m), dtype=int)
    temp = np.zeros((n, m), dtype=int)
    res[:, ::c] = temp[:, ::c]
    res[::r, :] = temp[::r, :]
    return res


n, m, r, c = (int(x) for x in input().split())
print(ex3(n, m, r, c))

6 7 2 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [25]:
def ex4(n, m):
    res = np.zeros((n, m), dtype=int)
    res[0, :] = np.arange(m)
    return res
    
n, m = (int(x) for x in input().split())
print(ex4(n, m))

4 5
[[0 1 2 3 4]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [26]:
def ex5(n):
    res = np.zeros((n, n), dtype=int)
    res[::2, :] = np.ones(n, dtype=int)
    return res

n = int(input())
print(ex5(n))

5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [27]:
def ex6(arr):
    arr[arr != 0] = -1
    return arr

n = np.array([int(x) for x in input().split()])
print(ex6(n))

1 2 3 0 9 0 7 0 3 1 0
[-1 -1 -1  0 -1  0 -1  0 -1 -1  0]


In [28]:
def ex7(arr):
    arr[arr == 0] = -1
    return arr

n = np.array([int(x) for x in input().split()])
print(ex7(n))

1 2 3 0 9 0 7 0 3 1 0
[ 1  2  3 -1  9 -1  7 -1  3  1 -1]


In [30]:
def ex8(arr):
    non = np.count_nonzero(arr)
    return non, arr.size - non

n = np.array([int(x) for x in input().split()])
res = ex8(n)
print("Non-zero:", res[0])
print('Zeros:', res[1])

1 2 3 0 9 0 7 0 3 1 0
Non-zero: 7
Zeros: 4


In [32]:
def ex9(n):
    return np.arange(n, -1, -1)

n = int(input())
print(ex9(n))

10
[10  9  8  7  6  5  4  3  2  1  0]


In [36]:
def ex10(n):
    arr = np.random.random((n, n))
    return np.min(arr), np.max(arr), np.mean(arr), np.std(arr)

n = int(input())
answ = ex10(n)
print("Min:", round(answ[0], 3))
print("Max:", round(answ[1], 3))
print("Mean:", round(answ[2], 3))
print("Standard deviation:", round(answ[3], 3))

5
Min: 0.001
Max: 0.937
Mean: 0.415
Standard deviation: 0.282


In [40]:
def ex11(n):
    res = np.ones((n, n), dtype=int)
    zeros = np.zeros((n, n), dtype=int)
    res[::n - 1, :] = zeros[::n - 1, :]
    res[:, ::n - 1] = zeros[:, ::n - 1]
    return res

n = int(input())
print(ex11(n))

5
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [41]:
def ex12(n):
    res = np.ones((n, n), dtype=float)
    zeros = np.zeros((n, n), dtype=float)
    res[::n - 1, :] = zeros[::n - 1, :]
    res[:, ::n - 1] = zeros[:, ::n - 1]
    return res

n = int(input())
print(ex11(n))

3
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [44]:
def ex13():
    print("In the matrix of 4x5x6 the 70-th element index is (2, 1, 3)")

ex13()

In the matrix of 4x5x6 the 70-th element index is (2, 1, 3)


In [89]:
def ex14():
    n = np.array([[0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0]])
    return np.repeat(n, repeats=4, axis=0).reshape(8, 8)

print(ex14())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [90]:
def ex15():
    n = np.array([[0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0]])
    return np.tile(n, repeats=4).reshape(8, 8)

print(ex14())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [92]:
def ex16(n):
    res = np.zeros((n, n), dtype=int)
    res[:, 1::2] = 1
    return res

n = int(input())
print(ex16(n))

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


In [15]:
def ex17(n):
    arr = np.random.randint(n, size=n)
    a = int(n / 2)
    b = int(3 * n / 4)
    arr[(arr > a) & (arr < b)] = 0
    return arr

n = int(input())
print(ex17(n))

20
10
15
[ 0 19  6  0  6  3  8 19 15 15  6  0 18  2  1 17  0  0  3  6]


In [30]:
def ex18(n):
    arr = np.random.randint(n, size=n)
    a = int(n / 2)
    b = int(3 * n / 4)
    arr[(arr > a) & (arr < b)] = -arr[(arr > a) & (arr < b)]
    return arr

n = int(input())
print(ex18(n))

20
[ 18 -11   6   0   2 -11  15 -12  15  10  16   3 -14  16   1   1  17  19
   3 -11]


In [32]:
def ex19(n):
    arr = np.random.randint(99, size=n)
    return arr, np.unique(arr).size

n = int(input())
res = ex19(n)
print(f"In {res[0]} there are {res[1]} unique elements")

30
In [ 0 44  6 48  6 23 79 50 70  4 31 27  6 13 98 64 12 26 59 34 59 90 87 82
 98 93 85 61 41 28] there are 26 unique elements


In [34]:
def ex20(n):
    return np.round(np.linspace(0, 1, n), 3)

n = int(input())
print(ex20(n))

20
[0.    0.053 0.105 0.158 0.211 0.263 0.316 0.368 0.421 0.474 0.526 0.579
 0.632 0.684 0.737 0.789 0.842 0.895 0.947 1.   ]


In [36]:
def ex21(n):
    res = np.random.random(n)
    maxt = np.max(res)
    return res, np.where(res==maxt, 0, res)

n = int(input())
res = ex21(n)
print("Array:", res[0])
print("Modified array:", res[1])

10
Array: [0.49790499 0.69107855 0.79615885 0.36254551 0.49229783 0.5710775
 0.9430144  0.89892233 0.97381654 0.49371805]
Modified array: [0.49790499 0.69107855 0.79615885 0.36254551 0.49229783 0.5710775
 0.9430144  0.89892233 0.         0.49371805]


In [44]:
def ex22(n, m):
    res = np.random.randint(m, size=(n, n))
    maxt = np.max(res)
    return res, np.where(res==maxt, -maxt, res)

n, m = (int(x) for x in input().split())
res = ex22(n, m)
print("Array:", res[0])
print("Modified array:", res[1])

3 10
Array: [[5 7 4]
 [9 6 4]
 [5 8 4]]
Modified array: [[ 5  7  4]
 [-9  6  4]
 [ 5  8  4]]


$$
sign(x) = \left\{
    \begin{array}\\
        x1 + 5x2 + 3x3 - 4x4 = 20\\
        3x1 + x2 - 2x3 = 9\\
        5x1 - 7x2 +10x4 = -9\\
        x2 +3x3 - 5x4 = 1
    \end{array}
\right.
$$

In [47]:
#Task2
import copy


def cramer(arr, n, m):
    a = copy.copy(arr[:, :m - 1])
    b = copy.copy(arr[:, m - 1])
    x = np.dot(np.linalg.inv(a), b)
    return np.linalg.solve(a, b), x

arr = np.array([[1, 5, 3, -4, 20], [3, 1, -2, 0 , 9], [5, -7, 0, 10, -9], [0, 3, -5, 0, 1]])
res = cramer(arr, 4, 5)
print(res[0])
print(res[1])
print(np.allclose(res[0], res[1]))

[ 3.  2.  1. -1.]
[ 3.  2.  1. -1.]
True


# A=
\begin{pmatrix}
5 & 2 & 0\\
10 & 4 & 1\\
7 & 3 & 2
\end{pmatrix}

# B=
\begin{pmatrix}
3 & 6 & -1\\
-1 & -2 & 0\\
2 & 1 & 3
\end{pmatrix}

$$
(A - B^{2}) * (A * 2 + B)
$$

In [55]:

#Task3
def movements(a, b):
    res = np.linalg.matrix_power(b, 2)
    res = np.subtract(a, res)
    res2 = np.add(np.dot(a, 2), b)
    return np.dot(res, res2)

a = [[5, 2, 0], [10, 4, 1], [7, 3, 2]]
b = [[3, 6, -1], [-1, -2, 0], [2, 1, 3]]
print(movements(a, b))

[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]


# A=
\begin{pmatrix}
2 & 3 & 1\\
4 & -1 & 0\\
0 & 1 & 2
\end{pmatrix}

# B=
\begin{pmatrix}
9 & 8 & 7\\
2 & 7 & 3\\
4 & 3 & 5
\end{pmatrix}

$$
A * X = B
$$

In [58]:
#Task4
def inverse(a, b):
    x = np.dot(np.linalg.inv(a), b)
    return np.linalg.solve(a, b), x

a = [[2, 3, 1], [4, -1, 0], [0, 1, 2]]
b = [[9, 8, 7], [2, 7, 3], [4, 3, 5]]
res = inverse(a, b)
print(res[0])
print(res[1])
print(np.allclose(res[0], res[1]))

[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]
True
